parameters:
#    tunisie_feeds.example.class: Tunisie\FeedsBundle\Example

services:
#    tunisie_feeds.example:
#        class: %tunisie_feeds.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
